routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\TransaksiController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [HomeController::class, 'index']);
Route::get('/home', [HomeController::class, 'index'])->middleware('auth')->name('home');

Route::resource('transaksi', TransaksiController::class)->only(['index', 'show']);
Route::resource('transaksi', TransaksiController::class)->except(['index', 'show'])->middleware('can:isAdminDeveloper');

Auth::routes();

app/Models/Description.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Description extends Model
{
    use HasFactory;

    protected $table = 'description';

    protected $fillable = [
        'transaksi_id',
        'description'
    ];

    public function transaksi()
    {
        return $this->belongsTo(Transaksi::class);
    }
}

app/Models/Transaksi.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Transaksi extends Model
{
    use HasFactory;
    protected $table = 'transaksi';
    protected $fillable = [
        'tanggal',
        'keterangan',
        'jumlah',
        'saldo',
        'kategori',
        'admin'
    ];

    public function description()
    {
        return $this->hasOne(Description::class);
    }

    public function users()
    {
        return $this->belongsTo(User::class);
    }
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function transaksi()
    {
        return $this->hasMany(Transaksi::class);
    }
}

app/Http/Controllers/API/TransaksiController.php
<?php

namespace App\Http\Controllers\API;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Transaksi;

class TransaksiController extends Controller
{
    public function filter(Request $request)
    {
        $data = [

            'dateFrom' => $request->dateFrom,
            'dateTo' => $request->dateTo,
            'kategori' => $request->kategori,
            'admin' => $request->admin
        ];

        var_dump($data);
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Transaksi;

class HomeController extends Controller
{
    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {


        $data = [
            'transaksi' => Transaksi::orderBy('tanggal', 'DESC')->limit(10)->get(),
            'title' => 'Dashboard'
        ];

        return view('index', $data);
    }
}

app/Http/Controllers/TransaksiController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Transaksi;
use App\Models\User;

class TransaksiController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = [
            'title'     => 'Riwayat Transaksi',
            'transaksi' => Transaksi::orderBy('tanggal', 'DESC')
                ->join('users', 'users.id', '=', 'transaksi.user_id')
                ->paginate(10),
            'users'      => User::all()
        ];

        return view('transaksi/index', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data = [
            'title' => 'Tambah Data'
        ];

        return view('tambahTransaksi', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return view('test');
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    {{ __('You are logged in!') }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/index.blade.php
@extends('layouts.master')
@section('content')
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-80">SALDO</h1>
    </div>

    <!-- Saldo  -->
    <div class="row text-center pt-5 saldo">
        <div class="container">
            <p>{{ 'Rp. ' . number_format($transaksi[0]->saldo, 2, ',', '.') }}</p>
        </div>
    </div>

    <!-- Content Row -->

    <div class="row">

        <!-- Area Chart -->
        <div class="col mt-5">
            <div class="card shadow mb-4 p-1">
                <!-- Card Header - Dropdown -->
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                    <h6 class="m-0 font-weight-bold text-primary">Rincian Transaksi Terbaru</h6>
                </div>
                <!-- Card Body -->
                <div class="table-responsive-lg">
                    <table class="table">
                        <thead class="thead-light">
                            <tr>
                                <th>Tanggal</th>
                                <th>Keterangan</th>
                                <th>Saldo Awal</th>
                                <th>Jumlah</th>
                                <th>Saldo</th>
                                <th>Kategori</th>
                                <th>Admin</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach( $transaksi as $t)
                                <tr class="{{ $t->kategori == 'MASUK' ? 'table-success' : 'table-danger' }}">
                                    <td>{{ $t->tanggal }}</td>
                                    <td>{{ $t->keterangan }}</td>
                                    <td>{{ 'Rp. ' . number_format($t->saldo - $t->jumlah, 2, ',', '.') }}</td>
                                    <td>{{ 'Rp. ' . number_format($t->jumlah, 2, ',', '.') }}</td>
                                    <td>{{ 'Rp. ' . number_format($t->saldo, 2, ',', '.') }}</td>
                                    <td>{{ $t->kategori }}</td>
                                    <td>{{ $t->admin }}</td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'kas-dusun') }}</title>

    <!-- Scripts -->
    {{-- <script src="{{ asset('js/app.js') }}" defer></script> --}}

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body id="page-top">
    <div id="app">
       
            <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
                <div class="container">
                    <a class="navbar-brand" href="{{ url('/') }}">
                        {{ config('app.name', 'Laravel') }}
                    </a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                        <span class="navbar-toggler-icon"></span>
                    </button>

                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <!-- Left Side Of Navbar -->
                        <ul class="navbar-nav mr-auto">

                        </ul>

                        <!-- Right Side Of Navbar -->
                        <ul class="navbar-nav ml-auto">
                            <!-- Authentication Links -->
                            @guest
                                @if (Route::has('login'))
                                    <li class="nav-item">
                                        <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                                    </li>
                                @endif
                                
                                @if (Route::has('register'))
                                    <li class="nav-item">
                                        <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                    </li>
                                @endif
                            @else
                                <li class="nav-item dropdown">
                                    <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                        {{ Auth::user()->name }}
                                    </a>

                                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                        <a class="dropdown-item" href="{{ route('logout') }}"
                                        onclick="event.preventDefault();
                                                      document.getElementById('logout-form').submit();">
                                            {{ __('Logout') }}
                                        </a>

                                        <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                            @csrf
                                        </form>
                                    </div>
                                </li>
                            @endguest
                        </ul>
                    </div>
                </div>
            </nav>

            <main class="py-4">
                @yield('content')
            </main>
    </div>
</body>
</html>

resources/views/layouts/master.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ $title }}</title>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

    <!-- Styles -->
    <link href="/css/sb-admin-2.css" rel="stylesheet">
    <link href="/css/style.css" rel="stylesheet">
</head>
<body id="page-top">
    <div id="wrapper">
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">
            
        <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center" href="/">
                <div>
                    <img class=" avatar" src="{{ asset('img/logo.png') }}" alt="">
                </div>
                <div class="sidebar-brand-text mx-3">KAS DUSUN</div>
            </a>

            <!-- Divider -->
            <hr class="sidebar-divider my-0">

            <!-- Nav Item - Dashboard -->
            <li class="nav-item active">
                <a class="nav-link" href="/">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Dashboard</span></a>
            </li>

            <!-- Riwayat Transaksi -->
            <li class="nav-item">
                <a class="nav-link" href="{{ route('transaksi.index') }}">
                    <i class="fas fa-fw fa-cog"></i>
                    <span>Riwayat Transaksi</span>
                </a>
            </li>

            <!-- Daftar Admin -->
            <li class="nav-item">
                <a class="nav-link" href="#">
                    <i class="fas fa-fw fa-wrench"></i>
                    <span>Daftar Admin</span>
                </a>
            </li>

            
            @auth
            <!-- Divider -->
            <hr class="sidebar-divider">
            <!-- Heading -->
                <div class="sidebar-heading">
                    Menu Management
                </div>

                <!-- Nav Item - Data Management -->
                @can('isAdminDeveloper')
                    <li class="nav-item">
                        <a class="nav-link" href="">
                            <i class="fas fa-fw fa-folder"></i>
                            <span>Data Management</span>
                        </a>
                    </li>
                @endcan
                @can('isDeveloper')
                    <li class="nav-item">
                        <a class="nav-link" href="">
                            <i class="fas fa-fw fa-folder"></i>
                            <span>Users Management</span>
                        </a>
                    </li>
                @endcan
            @endauth
            <!-- Divider -->
            <hr class="sidebar-divider d-none d-md-block">

            <!-- Sidebar Toggler (Sidebar) -->
            <div class="text-center d-none d-md-inline">
                <button class="rounded-circle border-0" id="sidebarToggle"></button>
            </div>
        </ul>
       
       <div id="content-wrapper" class="d-flex flex-column">
            <div id="content">
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                    <!-- Sidebar Toggle (Topbar) -->
                    <button id="sidebarToggleTop" class="btn btn-link d-lg-none rounded-circle mr-3">
                        <i class="fa fa-bars"></i>
                    </button>

                    <!-- Topbar Search -->
                    <form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
                        <div class="input-group">
                            <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
                            <div class="input-group-append">
                                <button class="btn btn-primary" type="button">
                                    <i class="fas fa-search fa-sm"></i>
                                </button>
                            </div>
                        </div>
                    </form>

                    <!-- Topbar Navbar -->
                     <ul class="navbar-nav ml-auto">

                        <!-- Nav Item - Search Dropdown (Visible Only XS) -->
                        <li class="nav-item dropdown no-arrow d-sm-none">
                            <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="fas fa-search fa-fw"></i>
                            </a>
                            <!-- Dropdown - Messages -->
                            <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in" aria-labelledby="searchDropdown">
                                <form class="form-inline mr-auto w-100 navbar-search">
                                    <div class="input-group">
                                        <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
                                        <div class="input-group-append">
                                            <button class="btn btn-primary" type="button">
                                                <i class="fas fa-search fa-sm"></i>
                                            </button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </li>
                        @guest
                            <li class="nav-item">
                                <a class="nav-link text-gray-600 font-weight-bold" href="{{ route('login') }}">Login</a>
                            </li>
                        @endguest
                        <div class="topbar-divider d-none d-sm-block"></div>

                        <!-- Nav Item - User Information -->
                        <li class="nav-item dropdown no-arrow">
                            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{ Auth::check() ? Str::upper(Auth::user()->name) : 'GUEST' }}</span>
                                <img class="img-profile rounded-circle" src="img/undraw_profile.svg">
                            </a>
                            <!-- Dropdown - User Information -->
                            @auth
                                <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
                                    <a class="dropdown-item" href="#" onclick="event.preventDefault(); document.getElementById('logout').submit();">
                                        <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                                        Logout
                                    </a>
                                    <form action="{{ route('logout') }}" method="POST" class="d-none" id="logout">
                                    @csrf
                                    </form>
                                </div>
                            @endauth
                        </li>
                    </ul>
                </nav>
                <div class="container-fluid p-2">

                    @yield('content')

                </div>
            </div>
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; kas-dusun 2020</span>
                    </div>
                </div>
            </footer>
       </div>       
    </div>
<a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
</a>
<!-- Logout Modal-->
<div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
            <div class="modal-footer">
                <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                <a class="btn btn-primary" href="login.html">Logout</a>
            </div>
        </div>
    </div>
</div>

<!-- Bootstrap core JavaScript-->
<script src="/vendor/jquery/jquery.min.js"></script>
<script src="/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

<!-- Core plugin JavaScript-->
<script src="/vendor/jquery-easing/jquery.easing.min.js"></script>

<!-- Custom scripts for all pages-->
<script src="{{ asset('js/sb-admin-2.js') }}"></script>

<script src="{{ asset('js/script.js') }}"></script>
</body>

</html>
</body>
</html>

resources/views/tambahTransaksi.blade.php
@extends('layouts/master')
@section('content')

	<div class="row">
        <!-- Area Chart -->
        <div class="col mt-5">
            <div class="card shadow mb-4 p-1">
                <!-- Card Header - Dropdown -->
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                    <h6 class="m-0 font-weight-bold text-primary">Rincian Transaksi Terbaru</h6>
                </div>
                <!-- Card Body -->
                <div class="table-responsive-lg">
                    <table class="table">
                        <thead class="thead-light">
                            <tr>
                                <th>Tanggal</th>
                                <th>Keterangan</th>
                                <th>Saldo Awal</th>
                                <th>Jumlah</th>
                                <th>Saldo</th>
                                <th>Kategori</th>
                                <th>Admin</th>
                            </tr>
                        </thead>
                        <tbody>
                           
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/test.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
	<title>Document</title>
</head>
<body>
	<h1>test</h1>
</body>
</html>

resources/views/transaksi/index.blade.php
@extends('layouts/master')
@section('content')

	<div class="row">
        <!-- Area Chart -->
        <div class="col mt-5">
            <div class="col mb-3">
                <button class="btn btn-info" id="filter">
                    <i class="fa fa-filter" aria-hidden="true"><span class="ml-2">Filter</span></i>
                </button>
            </div>
            
            <div class="card form-group border p-1 d-none" id="filterForm">
                <div class="card-header">
                    <h5 class="m-0 font-weight-bold">Filter</h5>
                </div>
                <div class="p-2 clearfix">
                    <div class="row">
                        <div class="col-md-6 mt-3">
                            <label for="">Tanggal:</label>
                            <div class="row">
                                <div class="col-md-5">
                                    <input type="date" name="dateFrom" class="form-control" id="dateFrom">
                                </div>
                                <div class="col-md-2 text-center"><h5 class="font-weight-bold">To</h5></div>
                                <div class="col-md-5">
                                    <input type="date" name="dateTo" class="form-control" id="dateTo">
                                </div>
                            </div>
                        </div>
                        <div class="col-md-3 mt-3">
                            <label for="kategori">Kategori:</label>
                            <select class="form-control" name="kategori" id="kategori">
                                <option value="">--Pilih Kategori--</option>
                                <option value="MASUK">PEMASUKAN</option>
                                <option value="KELUAR">PENGELUARAN</option>
                            </select>
                        </div>
                        <div class="col-md-3 mt-3">
                            <label for="admin">Admin:</label>
                            <select name="admin" id="admin" class="form-control">
                                <option value="">--Pilih Admin--</option>
                                @foreach($users as $u)
                                    <option value="{{ $u->id }}">{{ $u->name }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>

                    <button class="btn btn-success mt-3 float-right" id="show">Tampilkan</button>
                </div>

            </div>

            <div class="card shadow mb-4 p-1">
                <!-- Card Header - Dropdown -->
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                    <h6 class="m-0 font-weight-bold text-primary">Riwayat Transaksi</h6>
                </div>
                <!-- Card Body -->
                <div class="table-responsive-lg">
                    <table class="table">
                        <thead class="thead-light">
                            <tr>
                                <th>Tanggal</th>
                                <th>Keterangan</th>
                                <th>Saldo Awal</th>
                                <th>Jumlah</th>
                                <th>Saldo</th>
                                <th>Kategori</th>
                                <th>Admin</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody id="transaksi">
                            @foreach( $transaksi as $t)
                                <tr class="{{ $t->kategori == 'MASUK' ? 'table-success' : 'table-danger' }}">
                                    <td>{{ $t->tanggal }}</td>
                                    <td>{{ $t->keterangan }}</td>
                                    <td>{{ 'Rp. ' . number_format($t->saldo - $t->jumlah, 2, ',', '.') }}</td>
                                    <td>{{ 'Rp. ' . number_format($t->jumlah, 2, ',', '.') }}</td>
                                    <td>{{ 'Rp. ' . number_format($t->saldo, 2, ',', '.') }}</td>
                                    <td>{{ $t->kategori }}</td>
                                    <td>{{ $t->name }}</td>
                                    <td><h5><span class="badge badge-primary">Detail</span></h5></td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                
                        {{ $transaksi->onEachSide(3)->links() }}
                   
                </div>
            </div>
        </div>
    </div>
@endsection